### ISSUE TITLE
Use Digial Ocean's Floating IP

### ISSUE THREAD

**Issue by DocBradfordSoftware** [hermanjunge/k8s-do-tf#22]
I have tried to create a service that would make use of Digital Ocean's Floating IP. 

I have tried using the info here:
http://stackoverflow.com/questions/35884643/kubernetes-external-load-balancer-service-on-digitalocean
and here:
https://www.digitalocean.com/community/tutorials/how-to-use-floating-ips-on-digitalocean

without success.

So I have ended up attaching my nginx-proxy service to worker-0's external ip.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: default
  labels:
    k8s-app: nginx-proxy
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "nginx-proxy"
spec:
  selector:
    k8s-app: nginx-proxy
  ports:
  - name: http
    port: 80
    protocol: TCP
  externalIPs:
  - xxx.xxx.xxx.xxx
```

I'm not sure if the floating IP adds any value?
